#!/usr/bin/env bash
# check-frontend-coverage.sh — Phase 82 frontend coverage gate
# (GOV-03 global threshold + GOV-05 per-dir floor + D-10 whitelist drift).
#
# Reads the vitest v8-provider istanbul JSON (coverage-final.json, all-src
# caliber established by Phase 82-01), flattens it to TSV via inline node
# (the json is a 5.6MB single-line document — plain awk cannot parse it),
# aggregates STATEMENTS per directory at the D-05 granularity (src/ first-
# level dirs, pages/ split by second level, plus explicit "(src root)" and
# "api" entries so no area outside the whitelist is unowned), and enforces:
#   1. global weighted statements average >= the GLOBAL floor line (D-13/D-14)
#   2. every directory >= its per-dir floor from .coverage-fe-floors (D-07),
#      with bidirectional coverage: a floors entry missing from the profile
#      AND a profile directory missing from the floors table are both
#      violations (new directories may not skip the gate)
#   3. whitelist drift (D-10): cad-editor/cad-elements paths in the json
#      => fail fast, before any aggregation — coverage.exclude in
#      xingran-react-frontend/vitest.config.ts is the single truth source,
#      and polluted data must never enter the gate math
#
# Only the STATEMENTS dimension is used for gate decisions (D-13), mirroring
# the backend check-coverage.sh weighted-average caliber.
#
# Usage:
#   bash .github/scripts/check-frontend-coverage.sh <coverage-final.json> <floors-file>
#   bash .github/scripts/check-frontend-coverage.sh --init <coverage-final.json>
#
# Exit codes (mirror check-coverage.sh / check-status-literals.sh):
#   0 — global statements >= GLOBAL line AND all dirs >= floor AND no drift
#   1 — global threshold not met OR parse failure (no PASS line emitted)
#   2 — usage error (missing args / unreadable or malformed floors file)
#   4 — per-dir floor violation (GOV-05)
#   6 — whitelist drift: cad-editor/cad-elements present in the json (D-10)
#
# CI hookup (ci.yml frontend job, wired in Phase 82-04):
#   - name: Coverage gate
#     working-directory: .        # overrides the job-level working-directory
#                                 # (frontend job defaults to xingran-react-frontend/;
#                                 # without this override .github/scripts/ would not
#                                 # resolve and upload paths would be wrong too)
#     run: bash .github/scripts/check-frontend-coverage.sh \
#             xingran-react-frontend/coverage/coverage-final.json .coverage-fe-floors
#
# Ratchet workflow (D-06/D-07): floors live in .coverage-fe-floors at the repo
# root — bumping a floor is a pure data change, never a script change. The
# initial table is generated by --init (D-08) from the first all-src caliber
# run. Initial per-dir values are CONSERVATIVE LOWER BOUNDS, not pasted
# measurement values: floor = measured% - 0.5pp (lower bound 0). This mirrors
# the backend P2_RATCHET methodology (check-coverage.sh L230-241, PR #4
# round-5 lesson). Measurement-noise sources observed there:
#   - tool patch-version instrumentation drift: same code measured 754 stmts
#     locally vs 767 on CI (toolchain patch installs drift)
#   - env-branch divergence: tests take different branches on Linux CI vs
#     Windows local (backend agent/server 22.08% local vs 19.48% CI)
#   - async/timing variance across runs (device ±2 stmts)
# A floor pasted to a single measurement turns that noise into gate failures;
# the -0.5pp margin (D-06) absorbs it. Every bump of .coverage-fe-floors must
# land in the SAME commit as a row appended to
# .planning/frontend-coverage-baseline.md (backend D-04 discipline, applied to
# the frontend twin). Floors only move UP.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# ---------------------------------------------------------------------------
# 1. Arguments (exit 2 on usage errors)
# ---------------------------------------------------------------------------

INIT_MODE=0
if [ "${1:-}" = "--init" ]; then
  INIT_MODE=1
  shift
fi

PROFILE="${1:-}"
FLOORS_FILE="${2:-}"

usage_error() {
  echo "usage: $0 <coverage-final.json> <floors-file>" >&2
  echo "       $0 --init <coverage-final.json>" >&2
  echo "" >&2
  echo "  <coverage-final.json>  vitest json profile (xingran-react-frontend/coverage/...)" >&2
  echo "  <floors-file>          floor table at the repo root (.coverage-fe-floors)" >&2
  echo "" >&2
  echo "  --init                 regenerate floor initial values from the profile" >&2
  echo "                        (D-08; stdout is the new floors-file content)" >&2
  exit 2
}

if [ "$INIT_MODE" = "1" ]; then
  # --init takes exactly one argument (the json profile).
  if [ -z "$PROFILE" ] || [ -n "${2:-}" ]; then
    usage_error
  fi
else
  if [ -z "$PROFILE" ] || [ -z "$FLOORS_FILE" ]; then
    usage_error
  fi
fi

# Anchored floors path: relative paths resolve against the repo root so the
# gate reads the same file regardless of the caller's cwd (mirrors backend).
if [ "$INIT_MODE" = "0" ]; then
  case "$FLOORS_FILE" in
    /*) FLOORS_PATH="$FLOORS_FILE" ;;
    *)  FLOORS_PATH="$ROOT/$FLOORS_FILE" ;;
  esac

  if [ ! -f "$FLOORS_PATH" ]; then
    echo "check-frontend-coverage.sh: floors file $FLOORS_PATH not found" >&2
    exit 2
  fi
  if [ ! -r "$FLOORS_PATH" ]; then
    echo "check-frontend-coverage.sh: floors file $FLOORS_PATH not readable" >&2
    exit 2
  fi
fi

# Fail-safe: when no profile exists (Test step skipped or coverage not
# generated), don't fail the job — the upstream `if: always()` Upload step
# still wants to run for debug. Missing profile is a soft skip, not a hard
# gate failure (verbatim semantics from backend check-coverage.sh L77-85).
if [ ! -f "$PROFILE" ]; then
  echo "check-frontend-coverage.sh: coverage profile $PROFILE missing — was Test step skipped?" >&2
  echo "check-frontend-coverage.sh: skipping gate (exit 0) so Upload steps can still run with if: always()" >&2
  exit 0
fi

if [ ! -r "$PROFILE" ]; then
  echo "check-frontend-coverage.sh: coverage profile $PROFILE not readable" >&2
  exit 2
fi

# ---------------------------------------------------------------------------
# 2. Flatten the istanbul json to TSV (inline node — runner + frontend
#    toolchain standard runtime; zero third-party deps).
#
#    One line per file: relpath<TAB>stmts<TAB>covered<TAB>start-end:hit,...
#    Path normalization, three rules (Windows/CI dual compatible):
#      - backslashes -> forward slashes
#      - anchor "xingran-react-frontend/src/" matched case-insensitively
#      - relpath = anchor onward; keys outside src/ are skipped entirely
# ---------------------------------------------------------------------------

if ! FLAT="$(node -e '
const fs = require("fs");
const d = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
const out = [];
for (const p of Object.keys(d)) {
  const f = d[p] || {};
  const s = f.s || {};
  const sm = f.statementMap || {};
  const n = String(p).replace(/\\/g, "/");
  const i = n.toLowerCase().indexOf("xingran-react-frontend/src/");
  if (i < 0) continue;
  const rel = n.slice(i);
  let tot = 0, cov = 0;
  const ranges = [];
  for (const k of Object.keys(s)) {
    const m = sm[k];
    if (!m) continue;
    tot++;
    const hit = s[k] > 0;
    if (hit) cov++;
    ranges.push(m.start.line + "-" + m.end.line + ":" + (hit ? 1 : 0));
  }
  out.push(rel + "\t" + tot + "\t" + cov + "\t" + ranges.join(","));
}
process.stdout.write(out.join("\n") + (out.length > 0 ? "\n" : ""));
' "$PROFILE")"; then
  echo "check-frontend-coverage.sh: node flattening of $PROFILE failed — malformed json?" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 3. Whitelist drift detection (D-10) — fail fast, BEFORE aggregation.
#    Anchored to the truth-source PATH PREFIX (WR-02): the vitest exclude
#    globs are directory-prefix anchored and case-sensitive, so the drift
#    grep must be too — an unanchored substring match would false-positive
#    on legitimate paths like src/utils/cad-editor-helpers.ts.
# ---------------------------------------------------------------------------

if printf '%s\n' "$FLAT" | grep -Eq '^xingran-react-frontend/src/components/cad-(editor|elements)/'; then
  echo "check-frontend-coverage.sh: WHITELIST DRIFT (D-10) — cad-editor/cad-elements files present in the profile:" >&2
  printf '%s\n' "$FLAT" | grep -E '^xingran-react-frontend/src/components/cad-(editor|elements)/' | cut -f1 >&2
  echo "coverage.exclude in xingran-react-frontend/vitest.config.ts is the single truth source —" >&2
  echo "restore the exclusion and re-run coverage; do not let polluted data into the gate." >&2
  exit 6
fi

# ---------------------------------------------------------------------------
# 4. --init (D-08): regenerate floor initial values. No gate decisions here.
#    per-dir floor = max(0, round1(measured% - 0.5))   (D-06, noise margin)
#    GLOBAL        = min(measured%, 3.8), truncated DOWN to one decimal so a
#    generated threshold can never sit above the measured value (D-14).
# ---------------------------------------------------------------------------

if [ "$INIT_MODE" = "1" ]; then
  cat <<'INIT_HEADER'
# Frontend coverage floors (D-07) — generated by check-frontend-coverage.sh --init (D-08).
# Regenerate : bash .github/scripts/check-frontend-coverage.sh --init \
#              xingran-react-frontend/coverage/coverage-final.json
# Gate       : bash .github/scripts/check-frontend-coverage.sh \
#              xingran-react-frontend/coverage/coverage-final.json .coverage-fe-floors
# GLOBAL line (D-14): global statements threshold = min(measured, 3.8), one decimal.
# Dir lines: <directory><TAB>floor(%) — ratchet initial value = measured - 0.5pp,
# lower bound 0 (D-06 measurement-noise margin; never paste measured values).
# Ratchet bump = edit the numbers in THIS file only, never the script (D-07); every
# bump lands in the same commit as a row appended to
# .planning/frontend-coverage-baseline.md (floors only move UP).
INIT_HEADER
  INIT_OUT="$(awk -F'\t' '
    NF < 3 { next }
    {
      rest = $1
      sub(/^xingran-react-frontend\/src\//, "", rest)
      n = split(rest, seg, "/")
      if (n == 1) key = "(src root)"
      else if (seg[1] == "pages") key = "pages/" seg[2]
      else key = seg[1]
      d_stmts[key] += $2 + 0
      d_cov[key] += $3 + 0
      t_s += $2 + 0
      t_c += $3 + 0
    }
    END {
      if (length(d_stmts) == 0) exit 1
      gp = (t_s + 0 > 0) ? t_c * 100.0 / t_s : 0
      gv = (gp < 3.8 + 0) ? gp : 3.8
      gv = int(gv * 10 + 0.0000001) / 10
      printf "GLOBAL %.1f\n", gv
      n = 0
      for (k in d_stmts) keys[n++] = k
      for (i = 0; i < n - 1; i++) {
        for (j = i + 1; j < n; j++) {
          if (keys[j] < keys[i]) { tmp = keys[i]; keys[i] = keys[j]; keys[j] = tmp }
        }
      }
      for (i = 0; i < n; i++) {
        k = keys[i]
        s = d_stmts[k]; c = d_cov[k]
        pct = (s + 0 > 0) ? c * 100.0 / s : 0
        v = pct - 0.5
        if (v < 0) v = 0
        printf "%s\t%.1f\n", k, v
      }
    }
  ' <<< "$FLAT")" || { echo "check-frontend-coverage.sh: --init produced no rows — empty profile?" >&2; exit 1; }
  printf '%s\n' "$INIT_OUT"
  exit 0
fi

# ---------------------------------------------------------------------------
# 5. Parse the floors file: GLOBAL line (space-separated) + dir table
#    (<dir><TAB>floor). '#' comments and blank lines are allowed.
# ---------------------------------------------------------------------------

GLOBAL_FLOOR="$(awk '{ sub(/\r$/, "") } $1 == "GLOBAL" { print $2; exit }' "$FLOORS_PATH")"

case "$GLOBAL_FLOOR" in
  ''|*[!0-9.]*)
    echo "check-frontend-coverage.sh: floors file $FLOORS_FILE has no numeric GLOBAL line" >&2
    exit 2
    ;;
esac

# The GLOBAL line is space-separated while dir rows are TAB-separated, so it is
# excluded by matching the raw record (a tab-only FS would fold the whole GLOBAL
# line into $1 and never compare equal to "GLOBAL").
MALFORMED="$(awk -F'\t' '
  { sub(/\r$/, "") }
  /^#/ || /^GLOBAL([ \t]|$)/ || /^[[:space:]]*$/ { next }
  NF < 2 { print }
' "$FLOORS_PATH")"
if [ -n "$MALFORMED" ]; then
  echo "check-frontend-coverage.sh: malformed floor rows in $FLOORS_FILE (expected <dir><TAB>floor):" >&2
  printf '%s\n' "$MALFORMED" >&2
  exit 2
fi

DIR_TABLE="$(awk -F'\t' '
  { sub(/\r$/, "") }
  /^#/ || /^GLOBAL([ \t]|$)/ || /^[[:space:]]*$/ { next }
  NF >= 2 { print $1 "\t" $2 }
' "$FLOORS_PATH")"

# ---------------------------------------------------------------------------
# 6. Global gate (GOV-03, D-13/D-14): weighted statements average across all
#    files vs the GLOBAL line. Table rows use the backend format
#    "%-50s %8d %8d %6.2f%%" so local scans and CI logs are diff-friendly.
# ---------------------------------------------------------------------------

GLOBAL_TABLE="$(awk -F'\t' -v threshold="$GLOBAL_FLOOR" '
  NF < 3 { next }
  {
    rest = $1
    sub(/^xingran-react-frontend\/src\//, "", rest)
    n = split(rest, seg, "/")
    if (n == 1) key = "(src root)"
    else if (seg[1] == "pages") key = "pages/" seg[2]
    else key = seg[1]
    d_stmts[key] += $2 + 0
    d_cov[key] += $3 + 0
  }
  END {
    if (length(d_stmts) == 0) {
      printf "FAIL: empty profile (0 statements aggregated) — treating as failure\n"
      exit 1
    }
    total_s = 0
    total_c = 0
    for (k in d_stmts) {
      s = d_stmts[k]
      c = d_cov[k]
      pct = (s + 0 > 0) ? c * 100.0 / s : 0
      printf "%-50s %8d %8d %6.2f%%\n", k, s, c, pct
      total_s += s
      total_c += c
    }
    pkg_pct = (total_s + 0 > 0) ? total_c * 100.0 / total_s : 0
    printf "%-50s %8d %8d %6.2f%%\n", "TOTAL", total_s, total_c, pkg_pct
    if (pkg_pct + 0 < threshold + 0) {
      printf "FAIL: weighted avg %.2f%% < threshold %.2f%%\n", pkg_pct, threshold + 0
      exit 1
    } else {
      printf "PASS: weighted avg %.2f%% >= threshold %.2f%%\n", pkg_pct, threshold + 0
      exit 0
    }
  }
' <<< "$FLAT" || true)"

echo "$GLOBAL_TABLE"

if printf '%s\n' "$GLOBAL_TABLE" | grep -qE '^FAIL:'; then
  echo "" >&2
  echo "frontend coverage gate FAILED — global weighted statements average below $GLOBAL_FLOOR%" >&2
  echo "Bump the GLOBAL line of .coverage-fe-floors only as an intentional, documented" >&2
  echo "ratchet (same commit as a .planning/frontend-coverage-baseline.md row)," >&2
  echo "otherwise add tests to lift the weighted average back above the floor." >&2
  exit 1
fi

# Defensive tail (mirrors backend L149-154): if awk succeeded but no PASS line
# was emitted, treat it as a parse failure — the gate must never pass silently.
if ! printf '%s\n' "$GLOBAL_TABLE" | grep -qE '^PASS:'; then
  echo "check-frontend-coverage.sh: profile parsed but no PASS line emitted — treating as failure" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# 7. Per-dir floor gate (GOV-05, D-05/D-07). Two directions:
#      a) every floors entry must exist in the profile and sit above floor
#      b) every directory derived from the profile must be registered in the
#         floors table (unregistered new dirs are violations — no unowned
#         area outside the whitelist)
# ---------------------------------------------------------------------------

DIR_AGG="$(awk -F'\t' '
  NF < 3 { next }
  {
    rest = $1
    sub(/^xingran-react-frontend\/src\//, "", rest)
    n = split(rest, seg, "/")
    if (n == 1) key = "(src root)"
    else if (seg[1] == "pages") key = "pages/" seg[2]
    else key = seg[1]
    d_stmts[key] += $2 + 0
    d_cov[key] += $3 + 0
  }
  END {
    for (k in d_stmts) printf "%s\t%d\t%d\n", k, d_stmts[k], d_cov[k]
  }
' <<< "$FLAT")"

FLOOR_FAILED=0
PASS_COUNT=0
DIR_COUNT=0

# a) floors-registered directories vs the profile.
while IFS=$'\t' read -r fdir ffloor _; do
  [ -z "$fdir" ] && continue
  case "$ffloor" in
    ''|*[!0-9.]*)
      echo "check-frontend-coverage.sh: malformed floor value for '$fdir' in $FLOORS_FILE (got '${ffloor:-<empty>}')" >&2
      exit 2
      ;;
  esac
  DIR_COUNT=$((DIR_COUNT + 1))
  line="$(printf '%s\n' "$DIR_AGG" | awk -F'\t' -v p="$fdir" '$1 == p { print $2, $3; exit }')"
  if [ -z "$line" ]; then
    echo "FAIL: $fdir not found in profile — no statements measured for this directory" >&2
    FLOOR_FAILED=$((FLOOR_FAILED + 1))
    continue
  fi
  stmts="${line%% *}"
  covered="${line##* }"
  pct="$(awk -v s="$stmts" -v c="$covered" 'BEGIN { printf "%.2f", (s + 0 > 0) ? c * 100.0 / s : 0 }')"
  if awk -v a="$pct" -v b="$ffloor" 'BEGIN { exit !(a + 0 >= b + 0) }'; then
    echo "PASS: $fdir $pct% >= $ffloor% ($covered/$stmts stmts)"
    PASS_COUNT=$((PASS_COUNT + 1))
  else
    echo "FAIL: $fdir $pct% < $ffloor% ($covered/$stmts stmts)" >&2
    FLOOR_FAILED=$((FLOOR_FAILED + 1))
  fi
done <<< "$DIR_TABLE"

# b) profile-derived directories vs the floors table (unregistered = violation).
while IFS=$'\t' read -r dkey _; do
  [ -z "$dkey" ] && continue
  if ! printf '%s\n' "$DIR_TABLE" | awk -F'\t' -v p="$dkey" '$1 == p { found = 1 } END { exit !found }'; then
    echo "FAIL: $dkey 未登记 floor（新增目录必须入表）" >&2
    FLOOR_FAILED=$((FLOOR_FAILED + 1))
  fi
done <<< "$DIR_AGG"

if [ "$FLOOR_FAILED" -ne 0 ]; then
  echo "" >&2
  echo "frontend per-dir floor gate FAILED — $FLOOR_FAILED violation(s) (GOV-05)" >&2
  echo "Floors live in $FLOORS_FILE (D-07). Lift coverage with tests, or bump a floor" >&2
  echo "only as an intentional ratchet in the same commit as a baseline.md row." >&2
  exit 4
fi

echo "PASS: per-dir floor gate — $PASS_COUNT/$DIR_COUNT directories >= floor"
echo "frontend coverage gate passed (GLOBAL=$GLOBAL_FLOOR% + per-dir floors from $FLOORS_FILE)"
exit 0
